FROM timescale/timescaledb:2.2.0-pg13
ARG POSTGRESS_USER
ENV POSTGRESS_USER $POSTGRESS_USER
ARG POSTGRESS_PASSWORD
ENV POSTGRESS_PASSWORD $POSTGRESS_PASSWORD
ARG POSTGRESS_DB
ENV POSTGRESS_DB $POSTGRESS_DB
EXPOSE 5432
CMD ["postgres"]