spring:
  datasource:
    url: jdbc:mysql://localhost:3306/space-manager
    username: root
    password: Desapex@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: adarshshet09@gmail.com
    password: nwwpcudwlhxqqwdh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

